### ISSUE TITLE
Add support for RAR containers

### ISSUE THREAD

**Issue by C0D3D3V** [uktrade/stream-unzip#28]
Would it be possible to extend this project to support also other compression formats, like RAR?

**Comment by michalc** [comment]
Hello 👋 

While this is probably possible technically, I think other formats are beyond the scope of this project. In terms of RAR, I have to admit a lot of ignorance of it, but I believe it's an entirely different format, including a different compression algorithm. So a very rough guess of mine is that to add support for RAR would double the amount of code at the very least. And I fear it would probably require more dependencies. I have similar suspicions for other formats.

So if this project were extended to uncompress them, it would mean there would be effectively less time to support the main aim of this project: to stream unzip files. So as time goes on, it would be worse than it otherwise could be. More dependencies I think could also cause users of this project to spend more time unnecessarily, e.g. in response to published vulnerabilities.

So while I certainly see the value of something like what you suggest existing somewhere, e.g. for people that want to uncompress different formats, I'm afraid the answer is no, not in this repo. Of course, you are free to fork it and add support to the fork as long as you adhere to the license.
